# Generated by Django 4.2.13 on 2026-06-24 15:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("UHNW", "Ultra High Net Worth (>$30M)"),
                            ("HNW", "High Net Worth ($1M–$30M)"),
                            ("MA", "Mass Affluent ($250K–$1M)"),
                            ("INST", "Institutional"),
                        ],
                        default="HNW",
                        max_length=10,
                    ),
                ),
                ("onboarded_date", models.DateField()),
                ("kyc_verified", models.BooleanField(default=False)),
                ("kyc_verified_date", models.DateField(blank=True, null=True)),
                (
                    "risk_profile",
                    models.CharField(
                        choices=[
                            ("CONSERVATIVE", "Conservative"),
                            ("MODERATE", "Moderate"),
                            ("AGGRESSIVE", "Aggressive"),
                            ("VERY_AGGRESSIVE", "Very Aggressive"),
                        ],
                        default="MODERATE",
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(default="United States", max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("DISC", "Discretionary Managed"),
                            ("ADV", "Advisory"),
                            ("CUST", "Custody Only"),
                            ("TRUST", "Trust Account"),
                            ("RET", "Retirement (IRA/401k)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("inception_date", models.DateField()),
                ("benchmark", models.CharField(default="S&P 500", max_length=50)),
                ("base_currency", models.CharField(default="USD", max_length=3)),
                (
                    "market_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cash_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                (
                    "ytd_return",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=8
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="accounts.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-market_value"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("DIV", "Dividend"),
                            ("INT", "Interest"),
                            ("FEE", "Management Fee"),
                            ("TFI", "Transfer In"),
                            ("TFO", "Transfer Out"),
                            ("DEP", "Deposit"),
                            ("WIT", "Withdrawal"),
                        ],
                        max_length=5,
                    ),
                ),
                ("ticker", models.CharField(blank=True, max_length=20)),
                ("security_name", models.CharField(blank=True, max_length=255)),
                ("trade_date", models.DateField()),
                ("settlement_date", models.DateField()),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-trade_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "trade_date"],
                        name="accounts_tr_account_295e57_idx",
                    ),
                    models.Index(
                        fields=["ticker", "trade_date"],
                        name="accounts_tr_ticker_aa1dda_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=20)),
                ("security_name", models.CharField(max_length=255)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("EQ", "Equity"),
                            ("FI", "Fixed Income"),
                            ("ALT", "Alternative Investments"),
                            ("CASH", "Cash & Equivalents"),
                            ("RE", "Real Estate"),
                            ("COMM", "Commodities"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("cost_basis", models.DecimalField(decimal_places=4, max_digits=20)),
                ("market_price", models.DecimalField(decimal_places=4, max_digits=20)),
                ("market_value", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-market_value"],
                "unique_together": {("account", "ticker")},
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["tier", "is_active"], name="accounts_cl_tier_bfa109_idx"
            ),
        ),
    ]
