[pytest]
DJANGO_SETTINGS_MODULE = config.settings.development
python_files = test_*.py
python_paths = .
python_classes = Test*
python_functions = test_*
addopts =
    --reuse-db
    --strict-markers
    -ra
markers =
    unit: Unit tests (no DB)
    integration: Integration tests (requires DB)
    slow: Slow-running tests
