# Generated by Django 4.2.13 on 2026-06-24 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DAGRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dag_id", models.CharField(db_index=True, max_length=255)),
                ("dag_run_id", models.CharField(max_length=255, unique=True)),
                ("run_type", models.CharField(default="scheduled", max_length=50)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("execution_date", models.DateTimeField(db_index=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("conf", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-execution_date"],
            },
        ),
        migrations.CreateModel(
            name="TaskInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=20)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("try_number", models.IntegerField(default=1)),
                ("log_url", models.URLField(blank=True)),
                (
                    "dag_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_instances",
                        to="etl_monitor.dagrun",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="PipelineAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dag_id", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("WARNING", "Warning"),
                            ("INFO", "Info"),
                        ],
                        default="WARNING",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dag_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="etl_monitor.dagrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dagrun",
            index=models.Index(
                fields=["dag_id", "-execution_date"],
                name="etl_monitor_dag_id_4a3bbc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskinstance",
            unique_together={("dag_run", "task_id")},
        ),
    ]
