# Generated by Django 4.2.13 on 2026-06-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PerformanceAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(db_index=True, max_length=20)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("asset_class", models.CharField(max_length=10)),
                (
                    "allocation_effect",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                (
                    "selection_effect",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                (
                    "interaction_effect",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("total_effect", models.DecimalField(decimal_places=6, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="RiskMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("ACCOUNT", "Account"),
                            ("PORTFOLIO", "Portfolio"),
                            ("SECURITY", "Security"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        help_text="Account number, ticker, or portfolio ID",
                        max_length=50,
                    ),
                ),
                ("calculation_date", models.DateField(db_index=True)),
                (
                    "var_95_1d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="1-day 95% VaR as % of NAV",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "var_99_1d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="1-day 99% VaR as % of NAV",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "cvar_95_1d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Conditional VaR (Expected Shortfall)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "annualised_return",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "annualised_volatility",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "sortino_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "beta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "alpha",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "information_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "tracking_error",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "lookback_days",
                    models.IntegerField(
                        default=252, help_text="Rolling window in trading days"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-calculation_date"],
                "unique_together": {
                    ("scope", "reference_id", "calculation_date", "lookback_days")
                },
            },
        ),
        migrations.CreateModel(
            name="MarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=20)),
                ("security_name", models.CharField(max_length=255)),
                ("price_date", models.DateField(db_index=True)),
                ("open_price", models.DecimalField(decimal_places=4, max_digits=20)),
                ("high_price", models.DecimalField(decimal_places=4, max_digits=20)),
                ("low_price", models.DecimalField(decimal_places=4, max_digits=20)),
                ("close_price", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "adjusted_close",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                ("volume", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("source", models.CharField(default="INTERNAL", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-price_date"],
                "indexes": [
                    models.Index(
                        fields=["ticker", "-price_date"],
                        name="analytics_m_ticker_590d43_idx",
                    )
                ],
                "unique_together": {("ticker", "price_date")},
            },
        ),
        migrations.CreateModel(
            name="BenchmarkReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("benchmark_code", models.CharField(db_index=True, max_length=20)),
                ("benchmark_name", models.CharField(max_length=100)),
                ("return_date", models.DateField()),
                ("daily_return", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "cumulative_return",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("index_level", models.DecimalField(decimal_places=4, max_digits=15)),
            ],
            options={
                "ordering": ["-return_date"],
                "unique_together": {("benchmark_code", "return_date")},
            },
        ),
    ]
