# Generated by Django 4.2.13 on 2026-06-24 15:22

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetAllocationTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_profile", models.CharField(max_length=20, unique=True)),
                (
                    "equity_target_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "fixed_income_target_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "alternatives_target_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "cash_target_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "rebalance_threshold_pct",
                    models.DecimalField(decimal_places=2, default=Decimal("5.00"), max_digits=4),
                ),
                ("effective_date", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["risk_profile"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True)),
                ("total_aum", models.DecimalField(decimal_places=2, max_digits=22)),
                (
                    "equity_value",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=22),
                ),
                (
                    "fixed_income_value",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=22),
                ),
                (
                    "alternatives_value",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=22),
                ),
                (
                    "cash_value",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=22),
                ),
                (
                    "daily_pnl",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
                ),
                (
                    "daily_return_pct",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=8),
                ),
                (
                    "ytd_return_pct",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=8),
                ),
                ("client_count", models.IntegerField(default=0)),
                ("account_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-snapshot_date"],
                "unique_together": {("snapshot_date",)},
            },
        ),
    ]
